/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useSelector } from "react-redux";
import { useEffect } from "react";

const material = new THREE.MeshMatcapMaterial();
export default function Junior(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./JuniorJR_3_.glb");
  const { actions } = useAnimations(animations, group);
  // const texture = new THREE.TextureLoader().load(imageUrl);
  useEffect(() => {
    Object.keys(actions).forEach((key) => {
      actions[key].play();
    });
  }, []);
  // useEffect(() => {
  //   texture.wrapS = THREE.RepeatWrapping;
  //   texture.wrapT = THREE.RepeatWrapping;
  //   texture.minFilter = THREE.LinearFilter;
  //   texture.magFilter = THREE.LinearFilter;
  //   texture.needsUpdate = true;

  //   texture.encoding = THREE.sRGBEncoding;
  //   texture.needsUpdate = true;

  //   material.matcap = texture;
  //   material.needsUpdate = true;
  // }, [texture]);

  //   useFrame(() => {
  //     group.current.rotation.y += .002;
  //   })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_0"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_0"].geometry}
          material={materials.glass}
          position={[9.3, 0, -0.2]}
          rotation={[-Math.PI, 1.5, -Math.PI]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_1"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_1"].geometry}
          material={materials.luma}
          position={[9.3, 0, -0.2]}
          rotation={[-Math.PI, 1.5, 0]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_3"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_3"].geometry}
          material={materials.luma}
          position={[9.3, 0, -0.2]}
          rotation={[-Math.PI, 1.5, 0]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_4"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_4"].geometry}
          material={materials.luma}
          position={[9.3, 0, -0.2]}
          rotation={[-Math.PI, 1.5, 0]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_5"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_5"].geometry}
          material={materials.glass}
          position={[6.7, 0, 6.4]}
          rotation={[0, 1.1, Math.PI]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_6"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_6"].geometry}
          material={materials.luma}
          position={[6.7, 0, 6.4]}
          rotation={[0, -1, 0.5]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_8"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_8"].geometry}
          material={materials.glass}
          position={[6.7, 0, 6.4]}
          rotation={[0, 1.1, Math.PI]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_9"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_9"].geometry}
          material={materials.glass}
          position={[0.2, 0, 9.3]}
          rotation={[0, 0.3, Math.PI]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_10"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_10"].geometry}
          material={materials.luma}
          position={[0.2, 0, 9.3]}
          rotation={[-3.1, -1.3, -2.6]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_12"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_12"].geometry}
          material={materials.glass}
          position={[0.2, 0, 9.3]}
          rotation={[0, 0.3, Math.PI]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_13"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_13"].geometry}
          material={materials.glass}
          position={[-6.5, 0, 6.7]}
          rotation={[0, -0.8, 0]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_14"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_14"].geometry}
          material={materials.luma}
          position={[-6.5, 0, 6.7]}
          rotation={[0, -0.8, Math.PI]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_16"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_16"].geometry}
          material={materials.luma}
          position={[-6.5, 0, 6.7]}
          rotation={[0, -0.8, Math.PI]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_17"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_17"].geometry}
          material={materials.luma}
          position={[-6.5, 0, 6.7]}
          rotation={[0, -0.8, Math.PI]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_18"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_18"].geometry}
          material={materials.glass}
          position={[-9.3, 0, 0.2]}
          rotation={[0, -1.5, 0]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_19"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_19"].geometry}
          material={materials.luma}
          position={[-9.3, 0, 0.2]}
          rotation={[0, -1.5, -Math.PI]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_21"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_21"].geometry}
          material={materials.luma}
          position={[-9.3, 0, 0.2]}
          rotation={[0, -1.5, -Math.PI]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_22"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_22"].geometry}
          material={materials.luma}
          position={[-9.3, 0, 0.2]}
          rotation={[0, -1.5, -Math.PI]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_4v_&_M1__s07115_out_object_23"
          geometry={nodes["AS_ROMB_4v_&_M1__s07115_out_object_23"].geometry}
          material={materials.glass}
          position={[-6.7, 0, -6.5]}
          rotation={[3.1, -0.8, 2.7]}
          scale={[0.9, 0.8, 0.9]}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_26"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_26"].geometry}
          material={materials.glass}
          position={[-0.2, 0, -9.3]}
          rotation={[-Math.PI, -0.3, 0]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_27"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_27"].geometry}
          material={materials.luma}
          position={[-0.2, 0, -9.3]}
          rotation={[0, 1.3, 0.5]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_30"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_30"].geometry}
          material={materials.glass}
          position={[6.5, 0, -6.7]}
          rotation={[3.1, 0.8, 2.1]}
          scale={1.3}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_32"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_32"].geometry}
          material={materials.glass}
          position={[6.5, 0, -6.7]}
          rotation={[3.1, 0.8, 2.1]}
          scale={1.3}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_35"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_35"].geometry}
          material={materials.luma}
          position={[6.5, 0, -6.6]}
          rotation={[3.1, 0.8, 2.1]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_36"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_36"].geometry}
          material={materials.luma}
          position={[6.4, 0.1, -6.8]}
          rotation={[3.1, 0.8, 2]}
          scale={0.8}
        />
        <mesh
          name="AS_CUBE_2v_&_M0__s07115_out_object_39"
          geometry={nodes["AS_CUBE_2v_&_M0__s07115_out_object_39"].geometry}
          material={materials.glass}
          position={[3.8, 7, 1.5]}
          rotation={[0.2, -1.1, 2.6]}
          scale={0.5}
        />
        <mesh
          name="AS_CUBE_2v_&_M0__s07115_out_object_40"
          geometry={nodes["AS_CUBE_2v_&_M0__s07115_out_object_40"].geometry}
          material={materials.glass}
          position={[4.1, 6.8, 0]}
          rotation={[-1.6, -0.3, -2.1]}
          scale={0.5}
        />
        <mesh
          name="AS_CUBE_2v_&_M0__s07115_out_object_41"
          geometry={nodes["AS_CUBE_2v_&_M0__s07115_out_object_41"].geometry}
          material={materials.glass}
          position={[3.6, 5.9, 1.8]}
          rotation={[-1.9, -0.2, 2.4]}
          scale={0.5}
        />
        <mesh
          name="AS_CUBE_4v_&_M0__s07115_out_object_42"
          geometry={nodes["AS_CUBE_4v_&_M0__s07115_out_object_42"].geometry}
          material={materials.glass}
          position={[-0.1, 6.8, 5]}
          rotation={[3.1, 0, -1]}
          scale={1.1}
        />
        <mesh
          name="AS_CUBE_4v_&_M0__s07115_out_object_43"
          geometry={nodes["AS_CUBE_4v_&_M0__s07115_out_object_43"].geometry}
          material={materials.glass}
          position={[-0.1, 6.8, 3]}
          rotation={[3.1, 0, -1]}
          scale={1.1}
        />
        <mesh
          name="AS_CUBE_4v_&_M0__s07115_out_object_44"
          geometry={nodes["AS_CUBE_4v_&_M0__s07115_out_object_44"].geometry}
          material={materials.glass}
          position={[-0.9, 7.3, 4]}
          rotation={[3.1, 0, -1]}
          scale={1.1}
        />
        <mesh
          name="AS_CUBE_4v_&_M0__s07115_out_object_45"
          geometry={nodes["AS_CUBE_4v_&_M0__s07115_out_object_45"].geometry}
          material={materials.glass}
          position={[0.8, 6.3, 4]}
          rotation={[3.1, 0, -1]}
          scale={1.1}
        />
        <mesh
          name="AS_CUBE_4v_&_M0__s07115_out_object_46"
          geometry={nodes["AS_CUBE_4v_&_M0__s07115_out_object_46"].geometry}
          material={materials.glass}
          position={[-0.6, 6, 4]}
          rotation={[3.1, 0, -1]}
          scale={1.1}
        />
        <mesh
          name="AS_CUBE_4v_&_M0__s07115_out_object_47"
          geometry={nodes["AS_CUBE_4v_&_M0__s07115_out_object_47"].geometry}
          material={materials.glass}
          position={[0.4, 7.6, 4]}
          rotation={[3.1, 0, -1]}
          scale={1.1}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_49"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_49"].geometry}
          material={materials.glass}
          position={[-4, 6.8, -0.1]}
          rotation={[0.5, -0.5, 1.6]}
        />
        <mesh
          name="AS_CUBE_2v_&_M0__s07115_out_object_63"
          geometry={nodes["AS_CUBE_2v_&_M0__s07115_out_object_63"].geometry}
          material={materials.glass}
          position={[1.5, 7, -3.8]}
          rotation={[0.1, 0.5, 2.5]}
          scale={0.5}
        />
        <mesh
          name="AS_CUBE_2v_&_M0__s07115_out_object_64"
          geometry={nodes["AS_CUBE_2v_&_M0__s07115_out_object_64"].geometry}
          material={materials.glass}
          position={[0, 6.8, -4.1]}
          rotation={[-1.3, -0.1, -0.5]}
          scale={0.5}
        />
        <mesh
          name="AS_CUBE_2v_&_M0__s07115_out_object_65"
          geometry={nodes["AS_CUBE_2v_&_M0__s07115_out_object_65"].geometry}
          material={materials.glass}
          position={[1.8, 5.9, -3.6]}
          rotation={[-1.4, -0.4, -2.2]}
          scale={0.5}
        />
        <mesh
          name="AS_SPHERE_2v_&_M2__s07115_out_object_68"
          geometry={nodes["AS_SPHERE_2v_&_M2__s07115_out_object_68"].geometry}
          material={materials.glass}
          position={[-2.8, -4.9, 0.5]}
          rotation={[-0.1, 0.7, 0.1]}
          scale={0.5}
        />
        <mesh
          name="AS_SPHERE_5v_&_M2__s07115_out_object_70"
          geometry={nodes["AS_SPHERE_5v_&_M2__s07115_out_object_70"].geometry}
          material={materials.glass}
          position={[-1.2, -5, -2.6]}
          rotation={[1.3, -1, -1.7]}
          scale={0.5}
        />
        <mesh
          name="AS_SPHERE_5v_&_M2__s07115_out_object_71"
          geometry={nodes["AS_SPHERE_5v_&_M2__s07115_out_object_71"].geometry}
          material={materials.glass}
          position={[-2.1, -5.1, -2.7]}
          rotation={[1.3, -1, -1.7]}
          scale={0.1}
        />
        <mesh
          name="AS_SPHERE_5v_&_M2__s07115_out_object_73"
          geometry={nodes["AS_SPHERE_5v_&_M2__s07115_out_object_73"].geometry}
          material={materials.luma}
          position={[-0.9, -4.4, -2.3]}
          rotation={[1.3, -1, -1.7]}
          scale={0.4}
        />
        <mesh
          name="AS_SPHERE_5v_&_M2__s07115_out_object_74"
          geometry={nodes["AS_SPHERE_5v_&_M2__s07115_out_object_74"].geometry}
          material={materials.glass}
          position={[-1.3, -5, -2.8]}
          rotation={[1.3, -1, -1.7]}
          scale={0.5}
        />
        <mesh
          name="AS_SPHERE_5v_&_M2__s07115_out_object_75"
          geometry={nodes["AS_SPHERE_5v_&_M2__s07115_out_object_75"].geometry}
          material={materials.glass}
          position={[-1.3, -4.7, -3.3]}
          rotation={[1.3, -1, -1.7]}
          scale={1.3}
        />
        <mesh
          name="AS_SPHERE_3v_&_M2__s07115_out_object_77"
          geometry={nodes["AS_SPHERE_3v_&_M2__s07115_out_object_77"].geometry}
          material={materials.glass}
          position={[2.1, -5, -2.2]}
          rotation={[2.1, 0.5, -2.9]}
          scale={0.7}
        />
        <mesh
          name="AS_SPHERE_4v_&_M2__s07115_out_object_80"
          geometry={nodes["AS_SPHERE_4v_&_M2__s07115_out_object_80"].geometry}
          material={materials.glass}
          position={[2.5, -4.9, 1.2]}
          rotation={[1.9, -0.5, 1.1]}
          scale={1.2}
        />
        <mesh
          name="AS_SPHERE_4v_&_M2__s07115_out_object_81"
          geometry={nodes["AS_SPHERE_4v_&_M2__s07115_out_object_81"].geometry}
          material={materials.luma}
          position={[3.5, -5.1, 1]}
          rotation={[1.7, 0.6, 1.4]}
          scale={1.4}
        />
        <mesh
          name="AS_SPHERE_4v_&_M2__s07115_out_object_82"
          geometry={nodes["AS_SPHERE_4v_&_M2__s07115_out_object_82"].geometry}
          material={materials.luma}
          position={[3.3, -5, 1.5]}
          rotation={[1.7, 0.6, 1.4]}
          scale={1.4}
        />
        <mesh
          name="AS_SPHERE_4v_&_M2__s07115_out_object_83"
          geometry={nodes["AS_SPHERE_4v_&_M2__s07115_out_object_83"].geometry}
          material={materials.luma}
          position={[1.9, -4.7, 1.4]}
          rotation={[1.7, 0.6, 1.4]}
          scale={1.4}
        />
        <mesh
          name="AS_SPHERE_4v_&_M2__s07115_out_object_84"
          geometry={nodes["AS_SPHERE_4v_&_M2__s07115_out_object_84"].geometry}
          material={materials.luma}
          position={[1.6, -5.1, 1.1]}
          rotation={[1.7, 0.6, 1.4]}
          scale={1.4}
        />
        <mesh
          name="AS_SPHERE_4v_&_M2__s07115_out_object_85"
          geometry={nodes["AS_SPHERE_4v_&_M2__s07115_out_object_85"].geometry}
          material={materials.luma}
          position={[2.4, -4.9, 2.4]}
          rotation={[1.7, 0.6, 1.4]}
          scale={1.4}
        />
        <mesh
          name="AS_SPHERE_4v_&_M2__s07115_out_object_86"
          geometry={nodes["AS_SPHERE_4v_&_M2__s07115_out_object_86"].geometry}
          material={materials.glass}
          position={[2.7, -4.7, 1.4]}
          rotation={[1.7, 0.6, 1.4]}
          scale={1.4}
        />
        <mesh
          name="AS_SPHERE_4v_&_M2__s07115_out_object_87"
          geometry={nodes["AS_SPHERE_4v_&_M2__s07115_out_object_87"].geometry}
          material={materials.luma}
          position={[2.7, -4.8, -0.3]}
          rotation={[1.7, 0.6, 1.4]}
          scale={1.4}
        />
        <mesh
          name="AS_SPHERE_2v_&_M2__s07115_out_object_88"
          geometry={nodes["AS_SPHERE_2v_&_M2__s07115_out_object_88"].geometry}
          material={materials.glass}
          position={[-0.4, -4.9, 2.8]}
          rotation={[-3, 1.2, 3.1]}
          scale={0.5}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_2"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_2"].geometry}
          material={materials.metall_1}
          position={[9.3, 0, -0.2]}
          rotation={[-Math.PI, 1.5, -Math.PI]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_7"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_7"].geometry}
          material={materials.metall_1}
          position={[6.7, 0, 6.4]}
          rotation={[0, 1.1, Math.PI]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_11"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_11"].geometry}
          material={materials.metall_1}
          position={[0.2, 0, 9.3]}
          rotation={[0, 0.3, Math.PI]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_15"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_15"].geometry}
          material={materials.metall_1}
          position={[-6.5, 0, 6.7]}
          rotation={[0, -0.8, 0]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_1v_&_M1__s07115_out_object_20"
          geometry={nodes["AS_ROMB_1v_&_M1__s07115_out_object_20"].geometry}
          material={materials.metall_1}
          position={[-9.3, 0, 0.2]}
          rotation={[0, -1.5, 0]}
          scale={1.2}
        />
        <mesh
          name="AS_ROMB_4v_&_M1__s07115_out_object_24"
          geometry={nodes["AS_ROMB_4v_&_M1__s07115_out_object_24"].geometry}
          material={materials.metall_1}
          position={[-6.7, -0.6, -6.5]}
          rotation={[0, 0.8, -Math.PI]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_4v_&_M1__s07115_out_object_25"
          geometry={nodes["AS_ROMB_4v_&_M1__s07115_out_object_25"].geometry}
          material={materials.metall_1}
          position={[-6.7, 0.6, -6.5]}
          rotation={[0, 0.8, -Math.PI]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_28"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_28"].geometry}
          material={materials.metall_1}
          position={[-0.2, 0, -9.3]}
          rotation={[-Math.PI, -0.3, 0]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_5v_&_M1__s07115_out_object_29"
          geometry={nodes["AS_ROMB_5v_&_M1__s07115_out_object_29"].geometry}
          material={materials.metall_1}
          position={[-0.2, 0, -9.3]}
          rotation={[-Math.PI, -0.3, 0]}
          scale={0.9}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_31"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_31"].geometry}
          material={materials.metall_1}
          position={[6.5, 0, -6.7]}
          rotation={[Math.PI, 0.8, 0]}
          scale={1.3}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_33"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_33"].geometry}
          material={materials.metall_1}
          position={[6, 0, -6.3]}
          rotation={[3.1, 0.8, -1]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_34"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_34"].geometry}
          material={materials.metall_1}
          position={[6.3, -0.2, -6.8]}
          rotation={[3.1, 0.8, 2.1]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_37"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_37"].geometry}
          material={materials.metall_1}
          position={[6.6, 0.3, -6.6]}
          rotation={[3.1, 0.8, 1.9]}
          scale={0.8}
        />
        <mesh
          name="AS_ROMB_2v_&_M1__s07115_out_object_38"
          geometry={nodes["AS_ROMB_2v_&_M1__s07115_out_object_38"].geometry}
          material={materials.metall_1}
          position={[6.9, 0, -7.2]}
          rotation={[3.1, 0.8, 1.8]}
          scale={0.8}
        />
        <mesh
          name="AS_CUBE_4v_&_M0__s07115_out_object_48"
          geometry={nodes["AS_CUBE_4v_&_M0__s07115_out_object_48"].geometry}
          material={materials.metall_1}
          position={[-0.1, 6.8, 4]}
          rotation={[3.1, 0, 2.1]}
          scale={0.9}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_51"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_51"].geometry}
          material={materials.metall_1}
          position={[-3.9, 6.7, -0.3]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.7}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_53"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_53"].geometry}
          material={materials.metall_1}
          position={[-3.8, 7.2, -0.2]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.4}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_55"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_55"].geometry}
          material={materials.metall_1}
          position={[-4.3, 6.6, -0.4]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.5}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_56"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_56"].geometry}
          material={materials.metall_1}
          position={[-3.8, 6.5, -0.1]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.5}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_57"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_57"].geometry}
          material={materials.metall_1}
          position={[-3.9, 6.9, 0.1]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.7}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_58"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_58"].geometry}
          material={materials.metall_1}
          position={[-4.2, 7, -0.1]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.7}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_59"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_59"].geometry}
          material={materials.metall_1}
          position={[-4.1, 6.6, 0]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.7}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_61"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_61"].geometry}
          material={materials.metall_1}
          position={[-4.1, 6.9, 0.2]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.5}
        />
        <mesh
          name="AS_SPHERE_2v_&_M2__s07115_out_object_69"
          geometry={nodes["AS_SPHERE_2v_&_M2__s07115_out_object_69"].geometry}
          material={materials.metall_1}
          position={[-2.8, -4.9, 0.5]}
          rotation={[0, 0.7, -0.9]}
          scale={0.5}
        />
        <mesh
          name="AS_SPHERE_5v_&_M2__s07115_out_object_72"
          geometry={nodes["AS_SPHERE_5v_&_M2__s07115_out_object_72"].geometry}
          material={materials.metall_1}
          position={[-1.4, -4.6, -2.3]}
          rotation={[1.3, -1, -1.7]}
          scale={0.7}
        />
        <mesh
          name="AS_SPHERE_3v_&_M2__s07115_out_object_79"
          geometry={nodes["AS_SPHERE_3v_&_M2__s07115_out_object_79"].geometry}
          material={materials.metall_1}
          position={[2.1, -5.1, -2.2]}
          rotation={[3, -0.5, -1.3]}
          scale={0.7}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_50"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_50"].geometry}
          material={materials.metall_2}
          position={[-4, 6.8, -0.1]}
          rotation={[0.5, -0.5, 1.6]}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_52"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_52"].geometry}
          material={materials.metall_2}
          position={[-3.7, 6.8, -0.2]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.5}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_54"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_54"].geometry}
          material={materials.metall_2}
          position={[-4.1, 7, -0.5]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.4}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_60"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_60"].geometry}
          material={materials.metall_2}
          position={[-3.9, 6.7, 0.2]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.6}
        />
        <mesh
          name="AS_CUBE_3v_&_M0__s07115_out_object_62"
          geometry={nodes["AS_CUBE_3v_&_M0__s07115_out_object_62"].geometry}
          material={materials.metall_2}
          position={[-4.4, 6.8, 0]}
          rotation={[0.5, -0.5, 1.6]}
          scale={0.5}
        />
        <mesh
          name="AS_SPHERE_5v_&_M2__s07115_out_object_76"
          geometry={nodes["AS_SPHERE_5v_&_M2__s07115_out_object_76"].geometry}
          material={materials.metall_2}
          position={[-1.3, -4.9, -2.5]}
          rotation={[1.3, -1, -1.7]}
        />
        <mesh
          name="AS_SPHERE_3v_&_M2__s07115_out_object_78"
          geometry={nodes["AS_SPHERE_3v_&_M2__s07115_out_object_78"].geometry}
          material={materials.metall_2}
          position={[2.1, -5, -2.2]}
          rotation={[-2.7, 0.4, 2.2]}
          scale={0.7}
        />
        <mesh
          name="AS_SPHERE_2v_&_M2__s07115_out_object_89"
          geometry={nodes["AS_SPHERE_2v_&_M2__s07115_out_object_89"].geometry}
          material={materials.metall_2}
          position={[-0.4, -4.9, 2.8]}
          rotation={[-3.1, 1.2, 2.2]}
          scale={0.5}
        />
        <mesh
          name="Liquid_2_object_90"
          geometry={nodes.Liquid_2_object_90.geometry}
          // material={material}
          visible={false}
          position={[0.5, -0.2, -0.5]}
          rotation={[Math.PI / 2, 0, 0]}
          // map={texture ? texture : new THREE.Texture()}
          scale={0.0}
        />
        <mesh
          name="JuniorJR_3_ram"
          geometry={nodes.JuniorJR_3_ram.geometry}
          material={materials.ram}
          position={[0, 1.4, 0]}
          rotation={[Math.PI / 2, 0, 0.5]}
          scale={1.1}
        />
        <mesh
          name="JuniorJR_3_object_66"
          geometry={nodes.JuniorJR_3_object_66.geometry}
          material={materials.JuniorJR_3}
          position={[0, 1.4, 0]}
          rotation={[Math.PI / 2, 0, 0.5]}
          scale={1.1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./JuniorJR_3_.glb");
