/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import React from "react";
import { Float, useGLTF } from "@react-three/drei";
import { useSelector } from "react-redux";
import { useEffect } from "react";

export function Liquid(props) {
  const { nodes, materials } = useGLTF("/Untitled 1.glb");
  const material = new THREE.MeshMatcapMaterial();
  const { imageUrl } = useSelector((state) => state.imageUrl);
  // console.log(imageUrl)
  const texture = new THREE.TextureLoader().load(imageUrl);

  useEffect(() => {
    material.matcap = texture;
  }, [imageUrl]);

  return (
    <Float speed={5}>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Liquid_2_object_90.geometry}
          material={imageUrl ? material : materials.liquid}
          position={[0.5, -0.2, -0.48]}
          rotation={[0, 0.03, 0]}
          scale={130.9}
        />
      </group>
    </Float>
  );
}

useGLTF.preload("/Untitled 1.glb");
